In [1]:
import numpy as np

In [12]:
# np.random.seed(0)  # optional, for reproducibility

A1 = np.random.randint(-10, 11, size=(3, 3))
A2 = np.random.randint(-10, 11, size=(3, 3))
A3 = np.random.randint(-10, 11, size=(3, 3))

A1, A2, A3

(array([[ 2, -6, 10],
        [-2,  4,  5],
        [10, -7,  5]]),
 array([[  3,   6,   7],
        [ -5,  -1,  -7],
        [-10,  -5, -10]]),
 array([[ 7,  8, -6],
        [-8,  6, -7],
        [-8,  0,  3]]))

In [3]:
np.linalg.det(A1)

np.float64(936.9999999999999)

In [4]:
A1_inv = np.linalg.inv(A1)
A1_inv

array([[-0.03094984, -0.13874066, -0.09071505],
       [ 0.06296692,  0.00640342,  0.08110993],
       [-0.07470651, -0.02454642,  0.02241195]])

In [5]:
A2_inv = np.linalg.inv(A2)
A2_inv

array([[-0.36607143,  0.05357143, -0.17857143],
       [ 0.50892857, -0.19642857,  0.32142857],
       [ 0.41964286, -0.23214286,  0.10714286]])

In [6]:
A3_inv = np.linalg.inv(A3)
A3_inv

array([[ 0.21551724,  0.04310345, -0.00862069],
       [ 0.01149425,  0.06896552, -0.08045977],
       [-0.37643678, -0.00862069,  0.13505747]])

In [7]:
A1 @ A1_inv

array([[ 1.00000000e+00,  3.46944695e-17,  3.46944695e-17],
       [-2.77555756e-17,  1.00000000e+00, -1.42247325e-16],
       [ 1.11022302e-16,  1.38777878e-17,  1.00000000e+00]])

In [8]:
A2 @ A2_inv

array([[ 1.00000000e+00,  5.55111512e-17, -8.32667268e-17],
       [-2.77555756e-16,  1.00000000e+00, -9.71445147e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [9]:
A3 @ A3_inv

array([[ 1.00000000e+00,  3.46944695e-18, -2.77555756e-17],
       [-3.33066907e-16,  1.00000000e+00,  0.00000000e+00],
       [-2.98372438e-16,  5.55111512e-17,  1.00000000e+00]])